### PR TITLE
Bump dependancies for Laravel 9 compatibility.

### PR DESCRIPTION
**Pull request by leeovery**

### CODE REVIEW

**Review by REBELinBLUE — CHANGES_REQUESTED** [review]
Could you remove .phpunit.result.cache please

**Comment by leeovery** [comment]
Sorry for the delay. :)

**Comment by EdenMitchell** [comment]
Yes please 😄

**Comment by REBELinBLUE** [comment]
Sorry, been away, will get this merged this evening

-----------------
Stephen Ball
***@***.***

**Comment by LukeJeffs** [comment]
Yes please :)

**Comment by REBELinBLUE** [comment]
Sorry been a manic week at work, 4 day weekend coming up though so I will definitely get it done tomorrow!

**Pull request merged**
