### PR TITLE
Update illuminate/support

### PR DESCRIPTION
**Pull request by benrolfe**
Added support for Laravel 6 and Laravel 7.

### CODE REVIEW

**Comment by cweiske** [comment]
You drop support for Laravel 5.x with that patch.

**Comment by benrolfe** [comment]
That's true - not sure how to cater for both going forwards. Could you create a new major release? v2.0.0?

**Comment by REBELinBLUE** [comment]
So sorry, with everything which has been going on the last month I completely lost track of this, shall take a look after work this evening

**Comment by cweiske** [comment]
It is possible to specify multiple versions: https://getcomposer.org/doc/articles/versions.md#version-range

**Comment by benrolfe** [comment]
OK, I'll submit a new PR.

**Comment by REBELinBLUE** [comment]
Gah sorry, I ended up working late again on Friday and completely forgot. I've set myself an alarm to look at the PR this evening

**Pull request closed without merging**
